# Generated by Django 6.0.2 on 2026-03-16 01:16

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=50, validators=[apps.core.models.validate_email]),
        ),
        migrations.AlterField(
            model_name='technician',
            name='email',
            field=models.EmailField(max_length=50, validators=[apps.core.models.validate_email]),
        ),
    ]
